"""Pydantic schemas for PE-Nexus."""

from .deal import (
    ConnectionPath,
    DealCreate,
    DealStage,
    DealSummary,
    DiligenceChecklist,
    DiligenceItem,
    ICDecision,
    IndustryClassification,
    LegalFlag,
    LPReport,
    MasterDeal,
    PortfolioKPIs,
    StateTransition,
    TargetCompany,
    TeamMember,
    TracedDocument,
    TracedMemo,
)
from .events import (
    AgentTaskEvent,
    DealEvent,
    EventType,
    ExtractionEvent,
    ReviewEvent,
)
from .financials import (
    BoundingBox,
    Currency,
    EBITDAAdjustment,
    LBOAssumptions,
    LBOModelOutput,
    SensitivityTable,
    SourceReference,
    TracedFinancials,
    TracedValue,
)

__all__ = [
    # Deal
    "MasterDeal",
    "DealStage",
    "DealCreate",
    "DealSummary",
    "TargetCompany",
    "IndustryClassification",
    "TeamMember",
    "StateTransition",
    "TracedDocument",
    "ConnectionPath",
    "LegalFlag",
    "DiligenceItem",
    "DiligenceChecklist",
    "TracedMemo",
    "ICDecision",
    "PortfolioKPIs",
    "LPReport",
    # Financials
    "Currency",
    "BoundingBox",
    "SourceReference",
    "TracedValue",
    "EBITDAAdjustment",
    "TracedFinancials",
    "LBOAssumptions",
    "LBOModelOutput",
    "SensitivityTable",
    # Events
    "EventType",
    "DealEvent",
    "AgentTaskEvent",
    "ExtractionEvent",
    "ReviewEvent",
]
